#!/bin/bash

# Just enough bash to get ansible running. See ./README.md

set -eu -o pipefail

function main () {
  require_sudo
  (set -x && apt-get install -yq software-properties-common)
  (set -x && apt-add-repository --yes --update ppa:ansible/ansible)
  (set -x && apt-get update)
  (set -x && apt-get install -yq ansible)
  (set -x && ansible-galaxy install -r ./galaxy/requirements.yml)
  INVENTORY_DEFAULT=recipes/UNSPECIFIED
  INV_ARG=${1:-$INVENTORY_DEFAULT}
  if [ ! -e "$INV_ARG" ]; then
    >&2 echo "ERROR: Inventory file/dir '$INV_ARG' does not exist, or was not specified."
    exit 1
  fi
  (set -x && ansible-playbook playbooks/main.yml -i "$INV_ARG")
}

function require_sudo() {
  if [ $EUID -ne 0 ]; then
    >&2 echo "ERROR: Please run this script with sudo."
    exit 1
  fi
}

main "$@"
