---
basic_packages_redhat:
  - git
  - curl
  - libselinux-python
  - yum-utils
  - mlocate
  - htop
  - iotop
  - make
  - multitail
  - ncdu
  - nload
  - pv
  - tree
  - unzip
  - bc
  - screen

basic_packages_ubuntu:
  - git
  - curl
  - mcrypt
  - htop
  - iotop
  - make
  - multitail
  - ncdu
  - nload
  - nmon
  - pv
  - tree
  - unzip
  - bc
  - screen

set_bash_history_timestamps: true
