---
collections: []
roles:
- name: contrib/acromedia.essentials
  src: https://github.com/AcroMedia/ansible-role-essentials
  version: origin/master

- name: contrib/geerlingguy.ansible-role-pip
  src: https://github.com/geerlingguy/ansible-role-pip
  version: origin/master

- name: contrib/geerlingguy.ansible-role-docker
  src: https://github.com/dale-c-anderson/ansible-role-docker
  version: origin/382-fix-apt-errors-on-pop-os
