---
galaxy_info:
  author: Matt Breden
  description: Install packages commonly needed by Acro sysadmins and developers
  company: Acro Media Inc.
  license: AGPLv3

  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
      - trusty
      - xenial
      - bionic
  - name: EL
    versions:
      - 6

  galaxy_tags: []
dependencies: []
