---
- hosts: localhost
  connection: local
  become: true
  gather_facts: true
  roles:
    - name: Install sysadmin utils
      role: contrib/acromedia.essentials
      tags:
        - essentials

    - name: Install software on my workstation
      role: custom/workstation-packages
      tags:
        - workstation

    - name: Instal python pip, and packages
      role: contrib/geerlingguy.ansible-role-pip
      vars:
        pip_install_packages:
          - name: awscli   # @TODO - fix or replace this; it's still installing v1, we need v2
          - name: boto3
          - name: boto
          - name: docker
      tags:
        - pip

    - name: Instal docker Engine
      role: contrib/geerlingguy.ansible-role-docker
      tags:
        - docker

  tasks: []

- hosts: localhost
  connection: local
  become: true
  gather_facts: false
  tags:
    - gcloud
  tasks:
    - name: Install gcloud prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg

    - name: Configure apt source
      copy:
        dest: /etc/apt/sources.list.d/google-cloud-sdk.list
        content: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"

    - name: Install apt source key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
        #id: 7FAC5991
        keyring: /usr/share/keyrings/cloud.google.gpg

    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install gcloud cli
      apt:
        name: google-cloud-cli
        state: present
