---
- hosts: localhost
  connection: local
  become: true
  gather_facts: true
  roles:
    - name: Install sysadmin utils
      role: contrib/acromedia.essentials
      tags:
        - essentials

    - name: Install software on my workstation
      role: custom/workstation-packages
      tags:
        - workstation

    - name: Instal python pip, and packages
      role: contrib/geerlingguy.ansible-role-pip
      vars:
        pip_install_packages:
          - name: awscli
          - name: boto3
          - name: boto
      tags:
        - pip

  tasks: []
